
export const USERS_STORE_PROCEDURE = {
    USER_LOGIN: 'USER_LOGIN',
    USER_GET_DATA: 'USER_GET_DATA',
    USER_GET_LIST: 'USER_GET_LIST',
    USER_UPDATE_REFRESH_TOKEN: 'USER_UPDATE_REFRESH_TOKEN',
    USER_SAVE_REFRESH_TOKEN: 'USER_SAVE_REFRESH_TOKEN',
    USER_DEACTIVATE_ALL_TOKENS: 'USER_DEACTIVATE_ALL_TOKENS',
    USER_UPSERT_REFRESH_TOKEN: 'USER_UPSERT_REFRESH_TOKEN',
    USER_CHECK_ONETIME_LOGIN: 'User_Check_OneTime_Login',


}